### PR TITLE
feat: add WooCommerce integration

### PR DESCRIPTION
**Pull request by abhishek818**
Added scripts, validation tests and readme.

Fixes: #8 
/claim #8

### CODE REVIEW

**Review by HugoCasa — COMMENTED** [review]
Looks good, a few comments:
- the argument types have to be inlined directly in the function signature
- no need to specify return types
- i think you're assuming that the workspace instance is in a given state, you should make sure in the tests and/or in the setup.ts file to put the instance in that state

**Comment by abhishek818** [comment]
@HugoCasa  addressed your comments. Not sure about 3rd one. If anything missing related to it, do briefly explain.

**Comment by HugoCasa** [comment]
Thanks for the update!
- you still need to inline the type definitions of the function arguments directly in the function signature
- regarding my 3rd point, i need to be able to run the tests mysql after setting up a blank wordpress with woocommerce so for instance with Get_customer you're specifying a customer id which you need to make sure exists on the instance

**Comment by abhishek818** [comment]
@HugoCasa  Hey, thanks for the explanation. Have addressed everything.
Related to 3rd review comment, I am now calling GET apis to receive the customer/order/product IDs first and then passing it in respective GET/UPDATE apis. (in GET Customer/Order and Update Order/Product test files)

**Comment by HugoCasa** [comment]
I've tested it, it works!
Last things:
- you should make version in the resource optional 
- for the search customers endpoint you need to ensure that the customers actually exist (e.g. create them)
- suggestion: pass resource directly to WooCommerceRestApi instead of each individual property

**Comment by abhishek818** [comment]
@HugoCasa  Done, Up for review.

**Pull request merged**
