### PR TITLE
feat: zoom integration

### LINKED ISSUE #5: Write TypeScript scripts interacting with Zoom
Write TypeScript (Bun) scripts interacting with Zoom for the [Windmill Hub](https://hub.windmill.dev/).
The integration requires 15 scripts. You can find all the script descriptions in `src/integrations.yaml`.

Full instructions on how to do this can be found in the `README.md` file.

Get started by running `bun run setup zoom`.

### PR DESCRIPTION
**Pull request by neo773**
This PR adds zoom integration

/claim #5
/closes #5

### CODE REVIEW

**Comment by neo773** [comment]
@HugoCasa 
Hi,
Some API routes require a Zoom account with Pro plan, I don't have one so I'm stuck at my current progress.

image

**Review by HugoCasa — COMMENTED** [review]
Thanks for your PR!
Comments:
- the scripts should define the resource type and **not** import the resource from the resource.ts file. The resource has to be taken as argument (look at the github example in the repo)
- no need to handle errors
- you can't use types from the library for the function arguments, you have to write them explicitly

**Comment by neo773** [comment]
@HugoCasa 
This is ready to be reviewed, as for tests part I've kept it blank as I'm not sure to approach it, zoom requires users to confirm their email first and all the other tests depend on it.

**Comment by HugoCasa** [comment]
thanks for the update
- forgot to specify that function argument types have to be inlined inside the function signature sorry
- if the test requires a manual action, just write it down inside the test files

**Comment by neo773** [comment]
@HugoCasa 
Pushed

**Comment by neo773** [comment]
@HugoCasa 
Added the tests

**Comment by HugoCasa** [comment]
Thanks for the tests, i will try to run them.
One comment still:
- the scripts should define the resource type and **not** import the resource from the resource.ts file. The resource has to be taken as argument (look at the github example in the repo)

**Comment by neo773** [comment]
@HugoCasa 
Sorry about that, pushed!

**Comment by HugoCasa** [comment]
the type should be called Zoom

**Comment by neo773** [comment]
Should be all good now!

**Comment by HugoCasa** [comment]
Remark:
- the resource type json is missing
- the readme with the instructions to get the credentials is missing
- you changed the type name but not in the function signature
- please run the tests to check that the tests work

**Comment by neo773** [comment]
@HugoCasa 
Added json schema and README and fixed signature.
As for the tests some of these require a paid plan which I do not have, how should we proceed?
I've successfully tested the ones that don't require paid plan.

**Comment by HugoCasa** [comment]
which ones need a paid plan?

**Comment by neo773** [comment]
@HugoCasa 
This will require a webinar plan from Zoom.

image

image


- Add_Meeting_Registrant
- Add_Webinar_Registrant
- List_Past_Meeting_Participants
- List_Past_Webinar_Q&A
- List_Webinar_Participants_Report

**Comment by HugoCasa** [comment]
then you can ignore tests for those scripts

**Comment by neo773** [comment]
@HugoCasa 
Here's the test results
image

To run the tests, create a test meeting and two users, and channel id from `List_Channels`
```
ZOOM_USERID= \
ZOOM_MEETING_ID= \
ZOOM_EMAIL= \
ZOOM_DELETE_USER_ID= \
ZOOM_CREATE_USER_EMAIL= \
ZOOM_CHANNEL_ID= \
bun test
```

**Comment by HugoCasa** [comment]
i can't run the tests i get that error for all of them: 
Screenshot 2024-03-29 at 11 09 40

**Comment by HugoCasa** [comment]
nice, it works! 
- can you format the scripts with prettier respecting the .prettierrc file? 
- i don't think webhook secret token is required for these scripts. We can keep it but can you make it optional in resource_type.json?

**Comment by neo773** [comment]
@HugoCasa 
Pushed!

**Pull request merged**
