### PR TITLE
Feat: Linkedin Integration, fixes: #19

### PR DESCRIPTION
**Pull request by abhishek818**
Add typescripts, test cases and Readme file.

Fixes: #19 
/claim #19

### CODE REVIEW

**Comment by abhishek818** [comment]
@HugoCasa  Up for review.

**Comment by HugoCasa** [comment]
Looks good, few remarks:
- can you use fetch instead of axios?
- You should remove all the try catch wrapping (it's equivalent to throwing the caught error)

**Comment by abhishek818** [comment]
@HugoCasa  hey, tried fetch, but somehow it doesnt works and also makes the existing accessToken useless, I had to create new token to make it work with axios again. Tried this 2-3 times, returns 422 code and this suspicious access token behaviour. Weird, didnt found any lead to solve this.

Have removed try catch handling, Up for review.

**Comment by abhishek818** [comment]
sample fetch script:
type Linkedin = {
  userClientId: string;
  userClientSecret: string;
  userAccessToken: string;
  organizationClientId: string;
  organizationClientSecret: string;
  organizationAccessToken: string;
  baseUrl: string;
  apiVersion: string;
};

export async function main(
  resource: Linkedin,
  postData: {
    author: string;
    commentary: string;
    visibility: string;
    distribution: {
      feedDistribution: string;
      targetEntities: any[];
      thirdPartyDistributionChannels: any[];
    };
    content?: {
      media: {
        title: string;
        id: string;
      };
    };
    lifecycleState: string;
    isReshareDisabledByAuthor: boolean;
  },
) {
  const url = `${resource.baseUrl}/rest/posts`;
  return await fetch(url, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${resource.userAccessToken}`,
      'X-Restli-Protocol-Version': '2.0.0',
      'LinkedIn-Version': `${resource.apiVersion}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(postData),
  });
}

Test script: 
import { expect, test } from 'bun:test';
import { main } from './script.bun.ts';
import { resource } from '../resource.ts';
import { main as deleteUserPost } from '../Delete_Post/script.bun.ts';
import axios from 'axios';

test('Create a Simple Post (User)', async () => {
  // Get current user id' first, create post and delete it later.
  const userInfo = await axios.get(`${resource.baseUrl}/v2/userinfo`, {
    headers: {
      Authorization: `Bearer ${resource.userAccessToken}`,
      'X-Restli-Protocol-Version': '2.0.0',
      'LinkedIn-Version': `${resource.apiVersion}`,
    },
  });

  const userId = userInfo.data.sub;
  const response = await main(resource, {
    author: `urn:li:person:${userId}`,
    commentary: 'Sample text Post for the Windmill-Labs-Community, Testing LinkedIn developer apis',
    visibility: 'PUBLIC',
    distribution: {
      feedDistribution: 'MAIN_FEED',
      targetEntities: [],
      thirdPartyDistributionChannels: [],
    },
    lifecycleState: 'PUBLISHED',
    isReshareDisabledByAuthor: false,
  });

  expect(response.status).toBe(201);

  const postId = response.headers['x-restli-id'];
  // Delete the post
  await deleteUserPost(resource, postId);
});

**Comment by abhishek818** [comment]
> is apiVersion really needed? 
Yes its required, since versions will keep changing in future so chose it to keep as .env var.

**Comment by abhishek818** [comment]
> sample fetch script:
> 
> ```
> type Linkedin = {

@HugoCasa  hey, did you got time to check this?

**Comment by HugoCasa** [comment]
- I did not have time to check fetch, but could you try again? 
- for scripts that include images, you need to handle them as base 64 like for gcloud

**Comment by HugoCasa** [comment]
@abhishek818 still on it?

**Comment by abhishek818** [comment]
yep, will just get back to this.

**Comment by abhishek818** [comment]
@HugoCasa fetch somehow didnt worked, so axios remains.
Have addressed all other review comments.

**Comment by abhishek818** [comment]
@don't need values for both user and organization (you can juste duplicate resource.ts)
Duplicating resource.ts file would again need separate token .env vars, so have just went with a single file to keep it simple.
EX - 
user_resource.ts:
```
export const resource = {
	token: Bun.env.LINKEDIN_USER_ACCESS_TOKEN!, <--------------------------
	apiVersion: Bun.env.LINKEDIN_API_VERSION!
}
```
organization_resource.ts: 
```
export const resource = {
	token: Bun.env.LINKEDIN_ORGANIZATION_ACCESS_TOKEN!,  <---------------------
	apiVersion: Bun.env.LINKEDIN_API_VERSION!
}
```

**Comment by abhishek818** [comment]
@HugoCasa 

> i found the time to try with fetch and it works, i'm not sure what was your issue:

fetch works (it create the post on linkedin as intended), but also produces this error (though I always call the delete api to delete the post in my test scripts):
`
Create_a_Simple_Post__User_/script.bun.test.ts:
{
  errorDetailType: "com.linkedin.common.error.BadRequest",
  message: "com.linkedin.content.common.exception.BadRequestResponseException: Content is a duplicate of urn:li:share:7201530342036418560",
  errorDetails: {
    inputErrors: [
      [Object ...]
    ],
  },
  status: 422,
}
35 | 
36 |    // Check if the response status is 201
37 |    expect(response.status).toBe(201);
      ^
error: expect(received).toBe(expected)

Expected: 201
Received: 422

      at /workspaces/windmill-community-integrations/integrations/linkedin/Create_a_Simple_Post__User_/script.bun.test.ts:37:2`

**Comment by abhishek818** [comment]
> i don't think you handle correctly uploads post images (as string/base64), did you test that it works?
> you should also use the api to check if the action was a success (e.g. retrieve the created post)

deleting user/organization create image posts scripts as nothing works out, had also referred [link1 ](https://github.com/frozzel/uni-server/blob/6837e607eabcf83745c2b81540b69f49b49254d3/controllers/linkedin.js#L67) and [link2 ](https://github.com/frozzel/uni-server/blob/6837e607eabcf83745c2b81540b69f49b49254d3/controllers/linkedin.js#L67). My previous implementation did returned 200 success and i was able to delete it using delete api but it doesnt creates the post on Linkedin web.

Rest every script is working fine as intended..

**Pull request closed without merging**
