### PR TITLE
feat: add reddit integration

### PR DESCRIPTION
**Pull request by tarunrajput**
Fixes: https://github.com/windmill-labs/windmill-community-integrations/issues/7
/claim #7

### CODE REVIEW

**Review by HugoCasa — COMMENTED** [review]
Looks good but a few comments:
- each script has to be self-contained so you can't put common logic in a separate file
- for the two submit_ scripts, you also need to check using the api if the comment/post actually exists

**Comment by tarunrajput** [comment]
@HugoCasa, Thanks for revewing:
- I've moved the common logic to the scripts.
- IMO, for the submit scripts, the API will return an error if the submission is unsuccessful. Nevertheless, I've added an assertion check to confirm the post/comment actually exists. These two tests need to be run with slightly longer timeout though (default is 5s), as checking immediately after posting a comment results in comment not being found.

**Comment by HugoCasa** [comment]
Looks good! I've run the tests successfully.
Two last things:
- if the reddit username is required in the user agent string, you should pass it as a resource property
- you should change resource.ts to use env variables (Bun.env....) (and probably change your pwd ^^)

**Comment by dotslashtarun** [comment]
> if the reddit username is required in the user agent string, you should pass it as a resource property
it's not a requirement, hardcoded User-Agent will also work

> you should change resource.ts to use env variables (Bun.env....) (and probably change your pwd ^^)
Done

**Comment by HugoCasa** [comment]
the goal is to be able to use the script as is, so it's not ideal to have the user agent to be a placeholder for the user agent
i think the best solution would be to add an optional user agent property to the resource

**Comment by tarunrajput** [comment]
> the goal is to be able to use the script as is, so it's not ideal to have the user agent to be a placeholder for the user agent i think the best solution would be to add an optional user agent property to the resource

done

**Pull request merged**
