### PR TITLE
feat: todoist integration

### LINKED ISSUE #17: Write TypeScript scripts interacting with Todoist
Write TypeScript (Bun) scripts interacting with Todoist for the [Windmill Hub](https://hub.windmill.dev/).
The integration requires 42 scripts. You can find all the script descriptions in src/integrations.yaml.

Full instructions on how to do this can be found in the README.md file.

Get started by running `bun run setup todoist`.

### PR DESCRIPTION
**Pull request by neo773**
WIP PR for todoist integration.

/closes #17

### CODE REVIEW

**Comment by neo773** [comment]
@HugoCasa 
Hi,

this is ready for review

SCR-20240414-cwcw

image

image

I've set the timeout to 40 seconds as todoist API is quite slow and tests fail on Bun's default 5 second timeout
```
export TODOIST_TOKEN=""
export TODOIST_PROJECT_ID_READONLY=""
export TODOIST_COLLABORATOR_EMAIL=""

bun test --timeout 40000
```

**Comment by neo773** [comment]
Also I was wondering if the bounty could be adjusted based on the work, usually integrations have 10-20 scripts this one had 42

**Comment by neo773** [comment]
@HugoCasa 
About the types I don't think these can be inlined, they're pretty complex and depend on other types.
Let me know how you want to proceed.

image

**Comment by HugoCasa** [comment]
you can just simplify and include all properties as optional

**Comment by neo773** [comment]
@HugoCasa 
Added the changes to test also tested it.

**Comment by HugoCasa** [comment]
It's almost perfect:
- For Create project comment and Create task comment, in the function argument types, do not use "&" but merge them together
Once you're done, I'll merge

**Comment by neo773** [comment]
@HugoCasa 
Done

**Comment by HugoCasa** [comment]
i think you moved requestId inside args but shouldn't have right?

**Comment by neo773** [comment]
@HugoCasa 
My bad sorry!
Fixed

**Comment by HugoCasa** [comment]
@neo773 i think you need to claim the bounty here

**Comment by neo773** [comment]
Seems it's stuck now.
cc
@zcesur

**Comment by HugoCasa** [comment]
it's fine i can pay now

**Pull request merged**
